import streamlit as st
import pandas as pd
from datetime import datetime

# Basic Page Configuration
st.set_page_config(
    page_title="Standards Radar | Faria Education Group",
    page_icon="📡",
    layout="wide"
)

# --- SIDEBAR: LOGO & FILTERS ---
# Replace with the exact logo URL used in QA Auditor
LOGO_URL = "https://images.faria.org/logo.jpg" 

st.sidebar.image(LOGO_URL, use_container_width=True)
st.sidebar.caption("Standards & Services Department")
st.sidebar.divider()

st.sidebar.header("Filter Options")

# Main Page Header
st.title("📡 Standards Update Radar")
st.markdown("🔍 *Higher-level oversight for curriculum standards across global organizations.*")

try:
    # Load the data generated by the tracker
    df = pd.read_csv("auditoria_beta_v1.csv")

    # --- TOP METRICS ---
    c1, c2, c3 = st.columns(3)
    
    total_sites = len(df)
    alerts = len(df[df['Status'].str.contains("🚨")])
    last_sync = df['Check Date'].iloc[0] if not df.empty else "N/A"

    c1.metric("Total Sites", total_sites)
    c2.metric("Alerts Detected", alerts, delta=alerts, delta_color="inverse")
    c3.metric("Last Global Sync", last_sync)

    st.divider()

    # --- FILTER LOGIC ---
    search_org = st.sidebar.text_input("🔍 Search Organization", placeholder="e.g. Alabama")
    
    # Get unique status options for the filter
    status_options = df['Status'].unique().tolist()
    selected_status = st.sidebar.multiselect("Select Status", options=status_options, default=status_options)

    # Apply filters to the dataframe
    filtered_df = df[df['Status'].isin(selected_status)]
    if search_org:
        filtered_df = filtered_df[filtered_df['Organization'].str.contains(search_org, case=False)]

    # --- MAIN DATA TABLE ---
    st.subheader("Monitoring Log")
    
    # We use column_config to hide the Fingerprint and style the links
    st.dataframe(
        filtered_df,
        column_config={
            "Organization": st.column_config.TextColumn("Organization", width="medium"),
            "Subject": "Subject",
            "Status": st.column_config.TextColumn("Current Status"),
            "Check Date": "Last Verified",
            "Mapped Version": "Faria Reference",
            "URL": st.column_config.LinkColumn("Direct Link"),
            "Hash": None  # <--- THIS HIDES THE FINGERPRINT FROM THE UI
        },
        use_container_width=True,
        hide_index=True
    )

    # --- EXPORT OPTIONS ---
    st.sidebar.divider()
    st.sidebar.subheader("Export Data")
    
    # Convert the full dataframe (including Hashes) to CSV for the team
    full_csv = df.to_csv(index=False).encode('utf-8')
    
    st.sidebar.download_button(
        label="📥 Download Full CSV Report",
        data=full_csv,
        file_name=f"faria_standards_audit_{datetime.now().strftime('%Y%m%d')}.csv",
        mime="text/csv",
        help="Download the complete report including digital fingerprints for technical audit."
    )

except FileNotFoundError:
    st.info("🛰️ **System Update in Progress:** Data is being synchronized for the first time. Please run the GitHub Action or wait a few minutes.")
except Exception as e:
    st.error(f"An unexpected error occurred: {e}")

# Footer
st.markdown("---")
st.caption(f"© {datetime.now().year} Faria Education Group | Standards Radar v2.0 (High-Speed Engine)")
